# Generated by Django 6.1 on 2026-09-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='category',
        ),
        migrations.AddField(
            model_name='experience',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
