# Generated by Django 6.1 on 2026-09-26 02:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_service_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='service',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
